export async function getProducts() {
  return [
    {
      id: 1,
      name: "Nike Air Max",
      price: 150,
      category: "Кроссовки",
      colors: ["black", "yellow"],
      image: "/images/1.avif",
    },
    {
      id: 2,
      name: "Adidas Yeezy",
      price: 200,
      category: "Кроссовки",
      colors: ["blue", "black"],
      image: "/images/2.avif",
    },
    {
      id: 3,
      name: "T-shirt",
      price: 50,
      category: "Футболки",
      colors: ["brown"],
      image: "/images/3.avif",
    },
    {
      id: 4,
      name: "Puma RS-X",
      price: 120,
      category: "Футболки",
      colors: ["cadetblue", "lightskyblue"],
      image: "/images/4.avif",
    },
    {
      id: 5,
      name: "Puma RS-X",
      price: 150,
      category: "Кроссовки",
      colors: ["cornflowerblue", "black"],
      image: "/images/5.avif",
    },
    {
      id: 6,
      name: "Puma RS-X",
      price: 160,
      category: "Кроссовки",
      colors: ["yellow"],
      image: "/images/6.avif",
    },
    {
      id: 7,
      name: "Puma RS-X",
      price: 170,
      category: "Кроссовки",
      colors: ["pink"],
      image: "/images/9.avif",
    },
    {
      id: 8,
      name: "Puma RS-X",
      price: 250,
      category: "Кроссовки",
      colors: ["aqua"],
      image: "/images/8.avif",
    },
  ];
}
